#!/usr/bin/with-contenv bash

#------------------------------------------------------------------------------
# Install Jeedom cron
#------------------------------------------------------------------------------
if [ $(crontab -l | grep jeedom | wc -l) -ne 0 ];then
		(echo crontab -l | grep -v "jeedom") | crontab -
fi
if [ ! -f /etc/cron.d/jeedom ]; then
	echo "* * * * * www-data /usr/bin/php ${JEEDOM_VOL}/core/php/jeeCron.php >> /dev/null" > /etc/cron.d/jeedom
fi
if [ ! -f /etc/cron.d/jeedom_watchdog ]; then
	echo "*/5 * * * * root /usr/bin/php ${JEEDOM_VOL}/core/php/watchdog.php >> /dev/null" > /etc/cron.d/jeedom_watchdog
fi
